namespace: fleet-mc-helm-external-example
helm:
  chart: https://github.com/alexandrev/helm-bwce/releases/download/0.2.0/bwce-0.2.0.tgz
targetCustomizations:
- name: local
  helm:
    values:
      # This is a YAML-formatted file.
      # Declare variables to be passed into your templates.
      securityContext:
        runAsUser: 2001
        fsGroup: 2001

      replicas: 1
      image: 
        imageName: 938784100097.dkr.ecr.eu-west-2.amazonaws.com/ems-sender:1.0.1
        pullPolicy: Always
        imagePullSecrets: regcred
      # define environment variables here as a map of key: value
      env:

      # enable this flag to use knative serve to deploy the app
      istio: 
        enable: true

      serviceAccountName: default

      hashicorp:
        inject:
          enabled: false
          role: internal-app
          secrets:
          - name: internal/data/database/config
            path: secret-database-config.txt
            template: |
                {{- with secret "internal/data/database/config" -}}
                postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
                {{- end -}}
        enabled: true
        url: http://vault:8200
        path: /secret/test
        auth: 
          type: token
          path: 
          token: hvs.VSyeD2YYtC6lX0qnihhSQGrd
          roleId : 
          secretId: 
          username: 
          password: 
          cacert: 
        namespace: 
        kv:
          version: 2


      service:
        enabled: true
        type: ClusterIP
        port: 8080
        mainProcess: Process
        annotations:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
      probePath:
        httpGet: /_ping
        port: 7777
      livenessProbe:
        initialDelaySeconds: 180
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 1
      readinessProbe:
        initialDelaySeconds: 0
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 1

      bwce:
        configmap:
          enabled: true
          internal: false
          properties: /Users/avazquez/Desktop/hashicorp_test-default.properties
          name: bwce-emssender
      # if configmap false
        log:
          level: WARN
          format: "JSON"
        jvm:
          javaopts: "-Dsun.net.http.allowRestrictedHeaders=true -Dbw.engine.enable.memory.saving.mode=true -Dbw.engine.enable.audit.events=true"
          javagcopts: "-XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:ShenandoahUncommitDelay=1000 -XX:ShenandoahGuaranteedGCInterval=5000"
        bwprofile: "Docker"
        configprofile: "internal"
        monitoring:
          enabled: true
          mainProcess: "Process" 
          labels:
          release: "prometheus" 
        opentracing:
          enabled: true
          javaopts: "-Dbw.engine.opentracing.enable=true"

  clusterSelector:
    matchLabels:
      env: local

- name: test
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
